# =========================================
# Build Stage
# =========================================

ARG PNPM_VERSION=12.4.1
FROM ghcr.io/pnpm/pnpm:${PNPM_VERSION} AS build

RUN pnpm runtime set node 22.23.2 -g

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm approve-builds core-js
RUN pnpm install
RUN pnpm add -D @rolldown/binding-linux-x64-gnu@1.2.8
RUN pnpm approve-builds core-js

COPY . .

RUN pnpm approve-builds core-js
RUN pnpm run build

# =========================================
# Production Stage
# =========================================

FROM nginx:stable AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]