FROM python:3.12-slim AS builder

WORKDIR /documentation

COPY requirements-docs.txt ./
RUN python -m pip install --no-cache-dir -r requirements-docs.txt

COPY mkdocs.yml ./
COPY docs ./docs

RUN mkdocs build --strict

FROM nginx:alpine

COPY docs-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /documentation/site /usr/share/nginx/html

EXPOSE 80
