metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

db_engine = "sqlite"

replication_factor = 1
consistency_mode = "consistent"

rpc_secret = "9bc1dd0261f6216cdd6f184a564fbf6a5d804910fb16cc8f0721bba938851b6b"

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "garage:3901"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"

[admin]
api_bind_addr = "0.0.0.0:3903"